repos:
  - repo: 'git://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: (README\.md)$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-json
  - repo: 'git://github.com/Lucas-C/pre-commit-hooks'
    rev: v1.1.9
    hooks:
      - id: remove-crlf
  - repo: git://github.com/pre-commit/mirrors-prettier
    rev: v2.2.0
    hooks:
      - id: prettier
  - repo: git://github.com/pre-commit/mirrors-jshint
    rev: v2.12.0
    hooks:
      - id: jshint
  - repo: git://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: markdownlint
  - repo: git://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: dockerfile_lint
